# Has separate flows for develop branch (automatic builds) and
# Merge Request (automatic builds)
definitions:
  app-artifacts: &appArtifacts # Section def
    - emulator.log
    - project/app/build/reports
    - project/app/build/outputs/androidTest-results
    - project/app/build/outputs/logs
    - project/app/build/outputs/**/*.apk
    - project/app/build/outputs/**/*.aab
    - project/app/build/outputs/**/mapping.txt
  lib-artifacts: &libArtifacts
    - emulator.log
    - projectlib/sample/build/reports
    - projectlib/sample/outputs/androidTest-results
    - projectlib/sample/build/outputs/logs
    - projectlib/sample/build/outputs/**/*.apk
    - projectlib/sample/build/outputs/**/*.aab
    - projectlib/sample/build/outputs/**/mapping.txt
    - projectlib/ProjectCodeName/build/reports
    - projectlib/ProjectCodeName/build/outputs/androidTest-results
    - projectlib/ProjectCodeName/build/outputs/logs
    - projectlib/ProjectCodeName/build/outputs/**/*.aar
    - projectlib/ProjectCodeName/build/outputs/**/mapping.txt
  generated-app-artifacts: &generatedAppArtifacts
    - emulator.log
    - p42app/app/build/reports
    - p42app/app/build/outputs/androidTest-results
    - p42app/app/build/outputs/logs
    - p42app/app/build/outputs/**/*.apk
    - p42app/app/build/outputs/**/*.aab
    - p42app/app/build/outputs/**/mapping.txt
  generated-lib-artifacts: &generatedLibArtifacts
    - emulator.log
    - p42lib/sample/build/reports
    - p42lib/sample/outputs/androidTest-results
    - p42lib/sample/build/outputs/logs
    - p42lib/sample/build/outputs/**/*.apk
    - p42lib/sample/build/outputs/**/*.aab
    - p42lib/sample/build/outputs/**/mapping.txt
    - p42lib/p42lib/build/reports
    - p42lib/p42lib/build/outputs/androidTest-results
    - p42lib/p42lib/build/outputs/logs
    - p42lib/p42lib/build/outputs/**/*.aar
    - p42lib/p42lib/build/outputs/**/mapping.txt
  debug-emails: &debugEmails
    - lauris.kruusamae@lab.mobi
    - harri.kirik@lab.mobi
    - siret.jorro@lab.mobi
  scripts:
    # App local setup
    - &stepTemplateLocalSetup
      name: Set up local properties and permissons and add google-services.json and keystores
      script: sh ci/setup_project.sh
    # Library local setup
    - &stepLibLocalSetup
      name: Set up local properties and permissions
      script: |
        cd projectlib
        chmod +x gradlew
        echo "sdk.dir=$ANDROID_SDK_ROOT" > "$FCI_BUILD_DIR/local.properties"
    # Generate app with creator script
    - &stepRunCreatorScriptApp
      name: Run project creator script and replace google-services.json and keystores in the generated project
      script: sh ci/run_app_creator.sh
    # Generate lib with creator script
    - &stepRunCreatorScriptLib
      name: Run project creator script
      script: sh ci/run_lib_creator.sh
    # Run app checkCode
    - &stepTemplateCheckCode
      name: Check code style and formatting
      script: |
        cd project
        ./gradlew checkCode
    # Run lib checkCode
    - &stepLibCheckCode
      name: Check code style and formatting
      script: |
        cd projectlib
        ./gradlew checkCode
    # Run generated app checkCode
    - &stepGeneratedAppCheckCode
      name: Check code style and formatting
      script: |
        cd p42app
        ./gradlew checkCode
    # Run generated lib checkCode
    - &stepGeneratedLibCheckCode
      name: Check code style and formatting
      script: |
        cd p42lib
        ./gradlew checkCode
    # Build app DEBUG
    - &stepTemplateBuildDebug
      name: Build Android
      script: |
        cd project
        ./gradlew clean buildAllDebug
    # Build library and sample app
    - &stepLibBuild
      name: Build library and sample app
      script: |
        cd projectlib
        ./gradlew clean buildAll
    # Build generated app DEBUG
    - &stepGeneratedAppBuildDebug
      name: Build Android
      script: |
        cd p42app
        ./gradlew clean buildAllDebug
    # Build generated app RELEASE
    - &stepGeneratedAppBuildRelease
      name: Build Android
      script: |
        cd p42app
        ./gradlew clean buildAllRelease
    # Build generated library and sample app
    - &stepGeneratedLibBuild
      name: Build library and sample app
      script: |
        cd p42lib
        ./gradlew clean buildAll
    # Start emulator
    - &stepStartEmulator
      name: Launch emulator
      script: |
        cd $ANDROID_HOME/tools
        emulator -avd emulator &
        adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'
    # Stop emulator
    - &stepStopEmulator
      name: Stop emulator
      script: |
        cd $ANDROID_HOME/tools
        adb emu kill
    # Run app tests
    - &stepTemplateRunTests
      name: Test Android
      script: |
        cd project
        sh ../ci/run_tests.sh
    # Run library sample app tests
    - &stepLibAppRunTests
      name: Test Android
      script: |
        cd projectlib
        sh ../ci/run_tests.sh
    # Run generated app tests
    - &stepGeneratedAppRunTests
      name: Test Android
      script: |
        cd p42app
        sh ../ci/run_tests.sh
    # Run generated lib sample app tests
    - &stepGeneratedLibRunTests
      name: Test Android
      script: |
        cd p42lib
        sh ../ci/run_tests.sh

# Flows
workflows:
  develop-template-builds:
    name: Dev template builds
    instance_type: linux_x2
    environment:
      java: 17
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: 'develop'
          include: true
          source: true
    scripts:
      - *stepTemplateLocalSetup
      - *stepTemplateCheckCode
      - *stepStartEmulator
      - *stepTemplateRunTests
      - *stepStopEmulator
      - *stepTemplateBuildDebug
    artifacts: *appArtifacts
    publishing:
      email:
        recipients: *debugEmails
  develop-lib-builds:
    name: Dev lib builds
    instance_type: linux_x2
    environment:
      java: 17
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: 'develop'
          include: true
          source: true
    scripts:
      - *stepLibLocalSetup
      - *stepLibCheckCode
      - *stepStartEmulator
      - *stepLibAppRunTests
      - *stepStopEmulator
      - *stepLibBuild
    artifacts: *libArtifacts
    publishing:
      email:
        recipients: *debugEmails
  release-generated-app-builds:
    name: Release builds
    instance_type: linux_x2
    environment:
      java: 17
      ruby: 2.6.10
    scripts:
      - name: Check 'main' branch
        script: if [ "$FCI_BRANCH" != "main" ]; then exit 1; fi
      - *stepRunCreatorScriptApp
      - *stepGeneratedAppCheckCode
      - *stepStartEmulator
      - *stepGeneratedAppRunTests
      - *stepStopEmulator
      - *stepGeneratedAppBuildRelease
    artifacts: *generatedAppArtifacts
    publishing:
      email:
        recipients: *debugEmails
  develop-generated-app-builds:
    name: Dev generated app builds
    instance_type: linux_x2
    environment:
      java: 17
      ruby: 2.6.10
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: 'develop'
          include: true
          source: true
    scripts:
      - *stepRunCreatorScriptApp
      - *stepGeneratedAppCheckCode
      - *stepStartEmulator
      - *stepGeneratedAppRunTests
      - *stepStopEmulator
      - *stepGeneratedAppBuildDebug
    artifacts: *generatedAppArtifacts
    publishing:
      email:
        recipients: *debugEmails
  develop-generated-lib-builds:
    name: Dev generated lib builds
    instance_type: linux_x2
    environment:
      java: 17
      ruby: 2.6.10
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: 'develop'
          include: true
          source: true
    scripts:
      - *stepRunCreatorScriptLib
      - *stepGeneratedLibCheckCode
      - *stepStartEmulator
      - *stepGeneratedLibRunTests
      - *stepStopEmulator
      - *stepGeneratedLibBuild
    artifacts: *generatedLibArtifacts
    publishing:
      email:
        recipients: *debugEmails
  merge-requests-template:
    name: Merge requests template
    instance_type: linux_x2
    environment:
      java: 17
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: 'develop'
          include: true
          source: false
      cancel_previous_builds: true
    scripts:
      - *stepTemplateLocalSetup
      - *stepTemplateCheckCode
      - *stepStartEmulator
      - *stepTemplateRunTests
      - *stepStopEmulator
      - *stepTemplateBuildDebug
    publishing:
      email:
        recipients: *debugEmails
        notify:
          success: false
  merge-requests-lib:
    name: Merge requests lib
    instance_type: linux_x2
    environment:
      java: 17
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: 'develop'
          include: true
          source: false
      cancel_previous_builds: true
    scripts:
      - *stepLibLocalSetup
      - *stepLibCheckCode
      - *stepStartEmulator
      - *stepLibAppRunTests
      - *stepStopEmulator
      - *stepLibBuild
    publishing:
      email:
        recipients: *debugEmails
        notify:
          success: false
  merge-requests-generated-app:
    name: Merge requests generated app
    instance_type: linux_x2
    environment:
      java: 17
      ruby: 2.6.10
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: 'develop'
          include: true
          source: false
      cancel_previous_builds: true
    scripts:
      - *stepRunCreatorScriptApp
      - *stepGeneratedAppCheckCode
      - *stepStartEmulator
      - *stepGeneratedAppRunTests
      - *stepStopEmulator
      - *stepGeneratedAppBuildDebug
    publishing:
      email:
        recipients: *debugEmails
        notify:
          success: false
  merge-requests-generated-lib:
    name: Merge requests generated lib
    instance_type: linux_x2
    environment:
      java: 17
      ruby: 2.6.10
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: 'develop'
          include: true
          source: false
      cancel_previous_builds: true
    scripts:
      - *stepRunCreatorScriptLib
      - *stepGeneratedLibCheckCode
      - *stepStartEmulator
      - *stepGeneratedLibRunTests
      - *stepStopEmulator
      - *stepGeneratedLibBuild
    publishing:
      email:
        recipients: *debugEmails
        notify:
          success: false
