# Has separate flows for develop branch (automatic builds) and
# Merge Request (automatic builds)
definitions:
  generated-app-artifacts: &generatedAppArtifacts
    - emulator.log
    - p42app/app/build/reports
    - p42app/app/build/outputs/androidTest-results
    - p42app/app/build/outputs/logs
    - p42app/app/build/outputs/**/*.apk
    - p42app/app/build/outputs/**/mapping.txt
  generated-lib-artifacts: &generatedLibArtifacts
    - emulator.log
    - p42lib/sample/build/reports
    - p42lib/sample/outputs/androidTest-results
    - p42lib/sample/build/outputs/logs
    - p42lib/sample/build/outputs/**/*.apk
    - p42lib/sample/build/outputs/**/mapping.txt
    - p42lib/p42lib/build/reports
    - p42lib/p42lib/build/outputs/androidTest-results
    - p42lib/p42lib/build/outputs/logs
    - p42lib/p42lib/build/outputs/**/*.aar
    - p42lib/p42lib/build/outputs/**/mapping.txt
  debug-emails: &debugEmails
    - lauris.kruusamae@lab.mobi
    - harri.kirik@lab.mobi
    - siret.jorro@lab.mobi
  scripts:
    # Generate app with creator script
    - &stepRunCreatorScriptApp
      name: Run project creator script and replace google-services.json and keystores in the generated project
      script: sh ci/run_app_creator.sh
    # Generate lib with creator script
    - &stepRunCreatorScriptLib
      name: Run project creator script
      script: sh ci/run_lib_creator.sh
    # Run generated app checkCode
    - &stepGeneratedAppCheckCode
      name: Check code style and formatting
      script: |
        cd p42app
        ./gradlew checkCode
    # Run generated lib checkCode
    - &stepGeneratedLibCheckCode
      name: Check code style and formatting
      script: |
        cd p42lib
        ./gradlew checkCode
    # Build generated app
    - &stepGeneratedAppBuild
      name: Build Android
      script: |
        cd p42app
        ./gradlew buildAllRelease
    # Build generated library and sample app
    - &stepGeneratedLibBuild
      name: Build library and sample app
      script: |
        cd p42lib
        ./gradlew buildAll
    # Start emulator
    - &stepStartEmulator
      name: Launch emulator
      script: |
        cd $ANDROID_HOME/tools
        emulator -avd emulator &
        adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'
    # Stop emulator
    - &stepStopEmulator
      name: Stop emulator
      script: |
        cd $ANDROID_HOME/tools
        adb emu kill
    # Run generated app tests
    - &stepGeneratedAppRunTests
      name: Test Android
      script: |
        cd p42app
        sh ../ci/run_tests.sh
    # Run generated lib sample app tests
    - &stepGeneratedLibRunTests
      name: Test Android
      script: |
        cd p42lib
        sh ../ci/run_tests.sh

# Flows
workflows:
  # Runs the project creator script and builds the debug and release versions of generated app
  develop-generated-app-builds:
    name: Dev generated app builds
    instance_type: linux_x2
    environment:
      java: 17
      ruby: 2.6.10
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: 'develop'
          include: true
          source: true
      cancel_previous_builds: true
    scripts:
      - *stepRunCreatorScriptApp
      - *stepGeneratedAppCheckCode
      - *stepGeneratedAppBuild
      - *stepStartEmulator
      - *stepGeneratedAppRunTests
      - *stepStopEmulator
    artifacts: *generatedAppArtifacts
    publishing:
      email:
        recipients: *debugEmails
  # Runs the project creator script and builds the generated library and sample app
  develop-generated-lib-builds:
    name: Dev generated lib builds
    instance_type: linux_x2
    environment:
      java: 17
      ruby: 2.6.10
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: 'develop'
          include: true
          source: true
      cancel_previous_builds: true
    scripts:
      - *stepRunCreatorScriptLib
      - *stepGeneratedLibCheckCode
      - *stepGeneratedLibBuild
      - *stepStartEmulator
      - *stepGeneratedLibRunTests
      - *stepStopEmulator
    artifacts: *generatedLibArtifacts
    publishing:
      email:
        recipients: *debugEmails
  # Runs the project creator script and builds the debug version of generated app
  merge-requests-generated-app:
    name: Merge requests generated app
    instance_type: linux_x2
    environment:
      java: 17
      ruby: 2.6.10
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: 'develop'
          include: true
          source: false
      cancel_previous_builds: true
    scripts:
      - *stepRunCreatorScriptApp
      - *stepGeneratedAppCheckCode
      - *stepGeneratedAppBuild
      - *stepStartEmulator
      - *stepGeneratedAppRunTests
      - *stepStopEmulator
    publishing:
      email:
        recipients: *debugEmails
        notify:
          success: false
  # Runs the project creator script and builds the generated library and sample app
  merge-requests-generated-lib:
    name: Merge requests generated lib
    instance_type: linux_x2
    environment:
      java: 17
      ruby: 2.6.10
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: 'develop'
          include: true
          source: false
      cancel_previous_builds: true
    scripts:
      - *stepRunCreatorScriptLib
      - *stepGeneratedLibCheckCode
      - *stepGeneratedLibBuild
      - *stepStartEmulator
      - *stepGeneratedLibRunTests
      - *stepStopEmulator
    publishing:
      email:
        recipients: *debugEmails
        notify:
          success: false
